name: collision
description: Collision Detection and 2D geometry library for Dart and/or Flutter.
version: 0.0.2
repository: https://github.com/xclud/dart_collision

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ^2.1.0

dev_dependencies:
  test: ^1.17.3
